// AUTO-GENERATED by scripts/generate-tools.ts — DO NOT EDIT MANUALLY
// Run `npm run generate` to regenerate from the current SDK types.
// Generated at: 2026-06-04T17:33:24.447Z

import {
  MidiTrack, AudioTrack, MidiClip, AudioClip, ClipSlot, Device, DeviceParameter, Simpler, TakeLane,
  type Song,
} from "@ableton-extensions/sdk";

// ─── Object finders ────────────────────────────────────────────────────────

function findTrack(song: Song<"1.0.0">, id: string) {
  const t = song.tracks.find(t => t.handle.id.toString() === id);
  if (!t) throw new Error(`Track "${id}" not found. Call song_get_tracks to refresh.`);
  return t;
}

function findScene(song: Song<"1.0.0">, id: string) {
  const s = song.scenes.find(s => s.handle.id.toString() === id);
  if (!s) throw new Error(`Scene "${id}" not found.`);
  return s;
}

function findClip(song: Song<"1.0.0">, id: string) {
  for (const track of song.tracks) {
    for (const slot of track.clipSlots) {
      if (slot.clip?.handle.id.toString() === id) return slot.clip;
    }
    for (const clip of track.arrangementClips) {
      if (clip.handle.id.toString() === id) return clip;
    }
  }
  throw new Error(`Clip "${id}" not found.`);
}

function findDevice(song: Song<"1.0.0">, id: string) {
  for (const track of [...song.tracks, ...song.returnTracks]) {
    for (const device of track.devices) {
      if (device.handle.id.toString() === id) return device;
    }
  }
  throw new Error(`Device "${id}" not found.`);
}

function findDeviceParameter(song: Song<"1.0.0">, id: string) {
  for (const track of [...song.tracks, ...song.returnTracks]) {
    for (const device of track.devices) {
      for (const param of device.parameters) {
        if (param.handle.id.toString() === id) return param;
      }
    }
  }
  throw new Error(`DeviceParameter "${id}" not found.`);
}

function findTakeLane(song: Song<"1.0.0">, id: string) {
  for (const track of song.tracks) {
    for (const lane of track.takeLanes) {
      if (lane.handle.id.toString() === id) return lane;
    }
  }
  throw new Error(`TakeLane "${id}" not found.`);
}

function serializeHandle(obj: { handle: { id: bigint } } | null) {
  if (!obj) return null;
  return { id: obj.handle.id.toString() };
}

function serializeResult(result: unknown): unknown {
  if (result === null || result === undefined) return null;
  if (typeof result === "object" && "handle" in (result as object)) {
    const obj = result as { handle: { id: bigint }; name?: string };
    return { id: obj.handle.id.toString(), name: obj.name ?? undefined };
  }
  return result;
}

function findByHandleClass(song: Song<"1.0.0">, cls: string, id: string): unknown {
  switch (cls) {
    case "Track": case "MidiTrack": case "AudioTrack": return findTrack(song, id);
    case "Scene": return findScene(song, id);
    case "Clip": case "MidiClip": case "AudioClip": return findClip(song, id);
    case "Device": return findDevice(song, id);
    case "DeviceParameter": return findDeviceParameter(song, id);
    case "TakeLane": return findTakeLane(song, id);
    default: throw new Error(`Cannot find object of class "${cls}" by ID`);
  }
}

// ─── Dispatcher ────────────────────────────────────────────────────────────

export async function executeGeneratedTool(
  song: Song<"1.0.0">,
  name: string,
  args: Record<string, unknown>
): Promise<unknown> {
  switch (name) {
    case "song_create_audio_track": {
      const _result = await song.createAudioTrack();
      return serializeResult(_result);
    }
    case "song_create_midi_track": {
      const _result = await song.createMidiTrack();
      return serializeResult(_result);
    }
    case "song_create_scene": {
      const _result = await song.createScene(args["index"] as number);
      return serializeResult(_result);
    }
    case "song_delete_track": {
      song.deleteTrack(findByHandleClass(song, "Track", args["track_id"] as string) as never);
      return { ok: true };
    }
    case "song_delete_scene": {
      song.deleteScene(findByHandleClass(song, "Scene", args["scene_id"] as string) as never);
      return { ok: true };
    }
    case "song_duplicate_track": {
      const _result = await song.duplicateTrack(findByHandleClass(song, "Track", args["track_id"] as string) as never);
      return serializeResult(_result);
    }
    case "song_duplicate_scene": {
      const _result = await song.duplicateScene(findByHandleClass(song, "Scene", args["scene_id"] as string) as never);
      return serializeResult(_result);
    }
    case "song_create_cue_point": {
      const _result = await song.createCuePoint(args["time"] as number);
      return serializeResult(_result);
    }
    case "song_delete_cue_point": {
      song.deleteCuePoint(findByHandleClass(song, "CuePoint", args["cuePoint_id"] as string) as never);
      return { ok: true };
    }
    case "track_create_take_lane": {
      const _obj = findTrack(song, args["track_id"] as string);
      const _result = await _obj.createTakeLane();
      return serializeResult(_result);
    }
    case "track_insert_device": {
      const _obj = findTrack(song, args["track_id"] as string);
      const _result = await _obj.insertDevice(args["deviceName"] as string, args["index"] as number);
      return serializeResult(_result);
    }
    case "track_delete_device": {
      const _obj = findTrack(song, args["track_id"] as string);
      _obj.deleteDevice(findByHandleClass(song, "Device", args["device_id"] as string) as never);
      return { ok: true };
    }
    case "track_duplicate_device": {
      const _obj = findTrack(song, args["track_id"] as string);
      const _result = await _obj.duplicateDevice(findByHandleClass(song, "Device", args["device_id"] as string) as never);
      return serializeResult(_result);
    }
    case "track_delete_clip": {
      const _obj = findTrack(song, args["track_id"] as string);
      _obj.deleteClip(findByHandleClass(song, "Clip", args["clip_id"] as string) as never);
      return { ok: true };
    }
    case "track_clear_clips_in_range": {
      const _obj = findTrack(song, args["track_id"] as string);
      _obj.clearClipsInRange(args["startTime"] as number, args["endTime"] as number);
      return { ok: true };
    }
    case "midi_track_create_midi_clip": {
      const _baseTrack = findTrack(song, args["midi_track_id"] as string);
      if (!(_baseTrack instanceof MidiTrack)) throw new Error("Track is not a MIDI track.");
      const _obj = _baseTrack;
      const _result = await _obj.createMidiClip(args["startTime"] as number, args["duration"] as number);
      return serializeResult(_result);
    }
    case "audio_track_create_audio_clip": {
      const _baseTrack = findTrack(song, args["audio_track_id"] as string);
      if (!(_baseTrack instanceof AudioTrack)) throw new Error("Track is not an Audio track.");
      const _obj = _baseTrack;
      const _result = await _obj.createAudioClip(args["args"] as never);
      return serializeResult(_result);
    }
    case "clip_slot_delete_clip": {
      const _track = findTrack(song, args["track_id"] as string);
      const _slotIdx = args["slot_index"] as number;
      const _obj = _track.clipSlots[_slotIdx];
      if (!_obj) throw new Error(`ClipSlot ${_slotIdx} not found.`);
      _obj.deleteClip();
      return { ok: true };
    }
    case "clip_slot_create_midi_clip": {
      const _track = findTrack(song, args["track_id"] as string);
      const _slotIdx = args["slot_index"] as number;
      const _obj = _track.clipSlots[_slotIdx];
      if (!_obj) throw new Error(`ClipSlot ${_slotIdx} not found.`);
      const _result = await _obj.createMidiClip(args["length"] as number);
      return serializeResult(_result);
    }
    case "clip_slot_create_audio_clip": {
      const _track = findTrack(song, args["track_id"] as string);
      const _slotIdx = args["slot_index"] as number;
      const _obj = _track.clipSlots[_slotIdx];
      if (!_obj) throw new Error(`ClipSlot ${_slotIdx} not found.`);
      const _result = await _obj.createAudioClip(args["args"] as never);
      return serializeResult(_result);
    }
    case "device_parameter_get_value": {
      const _obj = findDeviceParameter(song, args["device_parameter_id"] as string);
      const _result = await _obj.getValue();
      return serializeResult(_result);
    }
    case "device_parameter_set_value": {
      const _obj = findDeviceParameter(song, args["device_parameter_id"] as string);
      _obj.setValue(args["value"] as number);
      return { ok: true };
    }
    case "simpler_replace_sample": {
      const _rawDevice = findDevice(song, args["simpler_id"] as string);
      if (!(_rawDevice instanceof Simpler)) throw new Error("Device is not a Simpler");
      const _obj = _rawDevice;
      const _result = await _obj.replaceSample(args["filePath"] as string);
      return serializeResult(_result);
    }
    case "take_lane_create_midi_clip": {
      const _obj = findTakeLane(song, args["take_lane_id"] as string);
      const _result = await _obj.createMidiClip(args["startTime"] as number, args["duration"] as number);
      return serializeResult(_result);
    }
    case "take_lane_create_audio_clip": {
      const _obj = findTakeLane(song, args["take_lane_id"] as string);
      const _result = await _obj.createAudioClip(args["args"] as never);
      return serializeResult(_result);
    }
    case "song_set_tempo": {
      song.tempo = args["value"] as never;
      return { ok: true };
    }
    case "track_set_name": {
      const _obj = findTrack(song, args["track_id"] as string);
      _obj.name = args["value"] as never;
      return { ok: true };
    }
    case "track_set_mute": {
      const _obj = findTrack(song, args["track_id"] as string);
      _obj.mute = args["value"] as never;
      return { ok: true };
    }
    case "track_set_solo": {
      const _obj = findTrack(song, args["track_id"] as string);
      _obj.solo = args["value"] as never;
      return { ok: true };
    }
    case "track_set_arm": {
      const _obj = findTrack(song, args["track_id"] as string);
      _obj.arm = args["value"] as never;
      return { ok: true };
    }
    case "clip_set_name": {
      const _obj = findClip(song, args["clip_id"] as string);
      _obj.name = args["value"] as never;
      return { ok: true };
    }
    case "clip_set_looping": {
      const _obj = findClip(song, args["clip_id"] as string);
      _obj.looping = args["value"] as never;
      return { ok: true };
    }
    case "clip_set_color": {
      const _obj = findClip(song, args["clip_id"] as string);
      _obj.color = args["value"] as never;
      return { ok: true };
    }
    case "clip_set_muted": {
      const _obj = findClip(song, args["clip_id"] as string);
      _obj.muted = args["value"] as never;
      return { ok: true };
    }
    case "midi_clip_set_notes": {
      const _baseClip = findClip(song, args["midi_clip_id"] as string);
      if (!(_baseClip instanceof MidiClip)) throw new Error("Clip is not a MIDI clip.");
      const _obj = _baseClip;
      _obj.notes = args["value"] as never;
      return { ok: true };
    }
    case "audio_clip_set_warping": {
      const _baseClip = findClip(song, args["audio_clip_id"] as string);
      if (!(_baseClip instanceof AudioClip)) throw new Error("Clip is not an Audio clip.");
      const _obj = _baseClip;
      _obj.warping = args["value"] as never;
      return { ok: true };
    }
    case "audio_clip_set_warp_mode": {
      const _baseClip = findClip(song, args["audio_clip_id"] as string);
      if (!(_baseClip instanceof AudioClip)) throw new Error("Clip is not an Audio clip.");
      const _obj = _baseClip;
      _obj.warpMode = args["value"] as never;
      return { ok: true };
    }
    case "scene_set_name": {
      const _obj = findScene(song, args["scene_id"] as string);
      _obj.name = args["value"] as never;
      return { ok: true };
    }
    case "take_lane_set_name": {
      const _obj = findTakeLane(song, args["take_lane_id"] as string);
      _obj.name = args["value"] as never;
      return { ok: true };
    }
    default:
      throw new Error(`Unknown generated tool: ${name}`);
  }
}
